version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        patterns:
          - "black"
          - "flake8"
          - "mypy"
          - "pyflakes"
          - "pytest"
          - "python-dotenv"
          - "ruff"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "python"
