stages:
  - build
  - test

default:
  image: $DEFAULT_CI_IMAGE

variables:
  DEFAULT_CI_IMAGE: python:3.10

setup:
  stage: build
  script:
    - pip install .
  only:
      - ~ /^feature/

pytest:
  stage: test
  script:
    - pip install .
    - pip install pytest dotenv
    - pytest
  only:
    - main
    - develop

snyk:
  stage: test
  script:
    - snyk monitor --org=50d263d0-ae67-4586-a999-084b375b1ab2 --command=python3
  only:
    - main
