stages:
  - build
  - test

default:
  image: $DEFAULT_CI_IMAGE

variables:
  DEFAULT_CI_IMAGE: python:3.10

setup:
  stage: build
  rules:
    - when: always
    - if: $CI_COMMIT_BRANCH =~ /^feature/
      when: manual
  script:
    - pip install .

pytest:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"
  script:
    - pip install .
    - pytest

snyk:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - snyk monitor --org=50d263d0-ae67-4586-a999-084b375b1ab2 --command=python3
