from softenum import Softenum


class RansomGroup(str, Softenum):

    conti = "Conti"
    lockbit = "LockBit"
    hive = "Hive"
    everest = "Everest"
    vice_society = "Vice Society"
    avos_locker = "AvosLocker"
    grief = "Grief"
    pysa = "Pysa"
    marketo = "Marketo"
    midas = "Midas"
    cl0p = "Cl0p"
    alphv = "ALPHV (aka BlackCat)"
    cuba = "Cuba"
    snatch = "Snatch"
    lv = "LV"
    quantum = "Quantum"
    payload = "Payload"
    lorenz = "Lorenz"
    ragnar_locker = "Ragnar_Locker"
    ransomexx = "RansomEXX"
    suncrypt = "Suncrypt"
    sabbath = "Sabbath"
    arvin_club = "Arvin Club"
    entropy_hof = "Entropy Hall of Fall"
    pay2Key = "Pay2Key"
    rook = "Rook"
    lockdata_auction = "LockData Auction"
    atomsilo = "Atomsilo"
    team_news = "Team News"
    blacktor = "Bl@ckt0r"
    nightsky = "Night Sky"
    bian_lian = "BianLian"
    ransom_house = "RansomHouse"
    karakurt = "Karakurt"
